//////////////////////////////////////////////////////////////////////
// LibFile: digit_glyphs.scad
// Project: Glyph Dossier
// FileGroup: Character Registry
// FileSummary: Character-level dossiers for digits 0 through 9.
//////////////////////////////////////////////////////////////////////

DIGIT_GLYPHS = [
    glyph_dossier(
        "D_0",
        "0",
        "digit",
        "closed_ring",
        1,
        1,
        1,
        1,
        "digit_height",
        ["outer_curve", "counter", "continuous_ring"],
        ["counter_collapse", "ring_thickness_loss", "letter_confusion"],
        ["slashed_zero", "dotted_zero", "oval_width"],
        "primary",
        "Primary digit ring test and distinction from uppercase O."
    ),
    glyph_dossier(
        "D_1",
        "1",
        "digit",
        "stem_flag_base",
        1,
        1,
        0,
        0,
        "digit_height",
        ["main_stem", "possible_flag", "possible_base"],
        ["narrow_part", "flag_fragment", "base_fragment"],
        ["plain_stem", "top_flag", "bottom_base", "serifed"],
        "primary",
        "Primary font-variation and narrow-digit test."
    ),
    glyph_dossier(
        "D_2",
        "2",
        "digit",
        "curve_diagonal_base",
        1,
        1,
        0,
        0,
        "digit_height",
        ["upper_curve", "diagonal_transition", "bottom_bar"],
        ["curve_diagonal_cut", "bottom_bar_fragment", "thin_transition"],
        ["flat_or_curved_base", "diagonal_angle"],
        "primary",
        "Primary mixed curve, diagonal, and horizontal test."
    ),
    glyph_dossier(
        "D_3",
        "3",
        "digit",
        "double_open_bowl",
        1,
        1,
        0,
        0,
        "digit_height",
        ["upper_curve", "lower_curve", "central_waist"],
        ["waist_fragment", "curve_cut", "terminal_fragment"],
        ["upper_lower_balance", "flat_or_rounded_spine"],
        "coverage",
        "Tests two open curved lobes and a narrow waist."
    ),
    glyph_dossier(
        "D_4",
        "4",
        "digit",
        "crossbar_diagonal_stem",
        1,
        1,
        0,
        1,
        "digit_height",
        ["diagonal", "vertical_stem", "crossbar", "possible_counter"],
        ["form_substitution", "crossbar_cut", "counter_collapse", "junction_cut"],
        ["open_four", "closed_four", "crossbar_height"],
        "primary",
        "Primary digit form-variation and junction test."
    ),
    glyph_dossier(
        "D_5",
        "5",
        "digit",
        "top_stem_lower_curve",
        1,
        1,
        0,
        0,
        "digit_height",
        ["top_bar", "upper_stem", "lower_curve"],
        ["curve_stem_cut", "top_bar_fragment", "waist_fragment"],
        ["flat_or_curved_top", "lower_bowl_size"],
        "coverage",
        "Tests abrupt transition from rectilinear to curved geometry."
    ),
    glyph_dossier(
        "D_6",
        "6",
        "digit",
        "loop_open_tail",
        1,
        1,
        1,
        1,
        "digit_height",
        ["lower_loop", "counter", "upper_open_curve"],
        ["counter_collapse", "neck_cut", "terminal_fragment"],
        ["loop_size", "terminal_angle"],
        "coverage",
        "Tests one counter with an open upper continuation."
    ),
    glyph_dossier(
        "D_7",
        "7",
        "digit",
        "topbar_diagonal",
        1,
        1,
        0,
        0,
        "digit_height",
        ["top_bar", "long_diagonal", "possible_crossbar"],
        ["diagonal_cut", "top_bar_fragment", "crossbar_fragment"],
        ["crossed_seven", "plain_seven", "serifed"],
        "coverage",
        "Tests a long diagonal and optional crossbar."
    ),
    glyph_dossier(
        "D_8",
        "8",
        "digit",
        "double_closed_loop",
        1,
        1,
        2,
        2,
        "digit_height",
        ["upper_loop", "lower_loop", "two_counters", "central_waist"],
        ["counter_collapse", "waist_fragment", "loop_boundary_cut"],
        ["upper_lower_balance", "waist_width"],
        "primary",
        "Primary two-counter digit test."
    ),
    glyph_dossier(
        "D_9",
        "9",
        "digit",
        "loop_descending_tail",
        1,
        1,
        1,
        1,
        "digit_height",
        ["upper_loop", "counter", "lower_open_tail"],
        ["counter_collapse", "neck_cut", "tail_fragment"],
        ["loop_size", "tail_angle"],
        "coverage",
        "Tests one upper counter with a descending open continuation."
    )
];
