//////////////////////////////////////////////////////////////////////
// LibFile: lowercase_glyphs.scad
// Project: Glyph Dossier
// FileGroup: Character Registry
// FileSummary: Character-level dossiers for a through z.
//////////////////////////////////////////////////////////////////////

LOWERCASE_GLYPHS = [
    glyph_dossier(
        "L_a",
        "a",
        "lowercase",
        "bowl_terminal",
        1,
        1,
        1,
        1,
        "x_height",
        ["bowl", "counter", "terminal", "possible_stem"],
        ["counter_collapse", "terminal_fragment", "form_substitution"],
        ["single_storey", "double_storey", "terminal_shape"],
        "primary",
        "Primary lowercase form-variation test; storey form must be recorded."
    ),
    glyph_dossier(
        "L_b",
        "b",
        "lowercase",
        "ascender_bowl",
        1,
        1,
        1,
        1,
        "ascender",
        ["ascender_stem", "lower_bowl", "counter"],
        ["stem_bowl_cut", "counter_collapse", "ascender_fragment"],
        ["bowl_height", "stem_join"],
        "coverage",
        "Tests an ascender joined to a lower bowl."
    ),
    glyph_dossier(
        "L_c",
        "c",
        "lowercase",
        "open_curve",
        1,
        1,
        0,
        0,
        "x_height",
        ["open_curve", "terminals"],
        ["terminal_fragment", "gap_closure", "curve_faceting"],
        ["aperture_width", "terminal_angle"],
        "coverage",
        "Lowercase open-curve control glyph."
    ),
    glyph_dossier(
        "L_d",
        "d",
        "lowercase",
        "bowl_ascender",
        1,
        1,
        1,
        1,
        "ascender",
        ["lower_bowl", "counter", "right_ascender"],
        ["bowl_stem_cut", "counter_collapse", "ascender_fragment"],
        ["stem_join", "bowl_width"],
        "coverage",
        "Mirror-related counterpart to lowercase b."
    ),
    glyph_dossier(
        "L_e",
        "e",
        "lowercase",
        "loop_crossbar",
        1,
        1,
        1,
        1,
        "x_height",
        ["loop", "counter", "crossbar", "open_terminal"],
        ["counter_collapse", "crossbar_cut", "aperture_closure"],
        ["aperture_width", "crossbar_angle"],
        "coverage",
        "Tests a compact counter with a crossbar and open terminal."
    ),
    glyph_dossier(
        "L_f",
        "f",
        "lowercase",
        "ascender_hook_crossbar",
        1,
        1,
        0,
        0,
        "ascender",
        ["ascender", "hook", "crossbar"],
        ["crossbar_fragment", "hook_fragment", "overhang_extent"],
        ["descender_variant", "crossbar_length", "terminal_shape"],
        "coverage",
        "Tests a narrow ascender with small lateral features."
    ),
    glyph_dossier(
        "L_g",
        "g",
        "lowercase",
        "loop_descender",
        1,
        1,
        1,
        2,
        "descender",
        ["upper_bowl", "counter", "descender", "possible_lower_loop"],
        ["form_substitution", "counter_collapse", "descender_fragment", "neck_cut"],
        ["single_storey", "double_storey", "ear_shape", "lower_loop"],
        "primary",
        "Primary lowercase complexity test; one- and two-storey forms differ fundamentally."
    ),
    glyph_dossier(
        "L_h",
        "h",
        "lowercase",
        "ascender_arch",
        1,
        1,
        0,
        0,
        "ascender",
        ["ascender_stem", "shoulder", "arch", "right_stem"],
        ["shoulder_cut", "arch_fragment", "narrow_inner_gap"],
        ["shoulder_height", "terminal_shape"],
        "coverage",
        "Tests an ascender feeding one rounded shoulder."
    ),
    glyph_dossier(
        "L_i",
        "i",
        "lowercase",
        "dotted_stem",
        2,
        2,
        0,
        0,
        "x_height_dot",
        ["stem", "separate_dot"],
        ["dot_loss", "component_assignment", "stem_fragment"],
        ["dot_shape", "serif_form"],
        "primary",
        "Primary disconnected-component test."
    ),
    glyph_dossier(
        "L_j",
        "j",
        "lowercase",
        "dotted_descender",
        2,
        2,
        0,
        0,
        "descender_dot",
        ["separate_dot", "stem", "descender_hook"],
        ["dot_loss", "descender_fragment", "component_assignment"],
        ["hook_depth", "dot_shape"],
        "primary",
        "Primary test combining a disconnected dot and descender."
    ),
    glyph_dossier(
        "L_k",
        "k",
        "lowercase",
        "ascender_diagonal_fork",
        1,
        1,
        0,
        0,
        "ascender",
        ["ascender_stem", "upper_diagonal", "lower_diagonal", "junction"],
        ["junction_cut", "diagonal_fragment", "small_inner_corner"],
        ["junction_height", "diagonal_angle"],
        "coverage",
        "Compact diagonal-junction test."
    ),
    glyph_dossier(
        "L_l",
        "l",
        "lowercase",
        "ascender_stem",
        1,
        1,
        0,
        0,
        "ascender",
        ["single_ascender_stem"],
        ["narrow_part", "serif_fragment", "digit_confusion"],
        ["serifed", "sans_serif", "curved_terminal"],
        "coverage",
        "Tests a narrow tall glyph and confusion with digit one."
    ),
    glyph_dossier(
        "L_m",
        "m",
        "lowercase",
        "repeated_arch",
        1,
        1,
        0,
        0,
        "x_height",
        ["left_stem", "first_arch", "middle_stem", "second_arch", "right_stem"],
        ["arch_cut", "narrow_gap", "repetition_misalignment"],
        ["arch_roundness", "terminal_shape"],
        "primary",
        "Primary repeated-arch and multiple-gap test."
    ),
    glyph_dossier(
        "L_n",
        "n",
        "lowercase",
        "single_arch",
        1,
        1,
        0,
        0,
        "x_height",
        ["left_stem", "arch", "right_stem"],
        ["arch_cut", "narrow_gap", "shoulder_fragment"],
        ["arch_roundness", "terminal_shape"],
        "coverage",
        "Single-arch control glyph."
    ),
    glyph_dossier(
        "L_o",
        "o",
        "lowercase",
        "closed_ring",
        1,
        1,
        1,
        1,
        "x_height",
        ["outer_curve", "counter", "continuous_ring"],
        ["counter_collapse", "ring_thickness_loss", "curve_faceting"],
        ["oval_width", "stroke_contrast"],
        "coverage",
        "Lowercase ring and compact counter test."
    ),
    glyph_dossier(
        "L_p",
        "p",
        "lowercase",
        "descender_bowl",
        1,
        1,
        1,
        1,
        "descender",
        ["descender_stem", "upper_bowl", "counter"],
        ["descender_fragment", "bowl_cut", "counter_collapse"],
        ["stem_length", "bowl_height"],
        "coverage",
        "Tests a bowl attached to a descending stem."
    ),
    glyph_dossier(
        "L_q",
        "q",
        "lowercase",
        "bowl_descender",
        1,
        1,
        1,
        1,
        "descender",
        ["upper_bowl", "counter", "right_descender"],
        ["descender_fragment", "bowl_cut", "counter_collapse"],
        ["tail_shape", "bowl_width"],
        "coverage",
        "Mirror-related counterpart to lowercase p."
    ),
    glyph_dossier(
        "L_r",
        "r",
        "lowercase",
        "stem_shoulder",
        1,
        1,
        0,
        0,
        "x_height",
        ["left_stem", "shoulder", "terminal"],
        ["shoulder_fragment", "terminal_loss", "narrow_part"],
        ["shoulder_shape", "terminal_length"],
        "coverage",
        "Tests a small asymmetric shoulder."
    ),
    glyph_dossier(
        "L_s",
        "s",
        "lowercase",
        "reversing_curve",
        1,
        1,
        0,
        0,
        "x_height",
        ["upper_curve", "lower_curve", "narrow_waist"],
        ["waist_fragment", "curve_cut", "terminal_fragment"],
        ["upper_lower_balance", "terminal_angle"],
        "primary",
        "Primary compact reversing-curve test."
    ),
    glyph_dossier(
        "L_t",
        "t",
        "lowercase",
        "short_ascender_crossbar",
        1,
        1,
        0,
        0,
        "ascender",
        ["short_ascender", "crossbar", "lower_terminal"],
        ["crossbar_fragment", "top_fragment", "terminal_loss"],
        ["ascender_height", "crossbar_position", "curved_bottom"],
        "coverage",
        "Tests short lateral features on a narrow stem."
    ),
    glyph_dossier(
        "L_u",
        "u",
        "lowercase",
        "bottom_curve_stems",
        1,
        1,
        0,
        0,
        "x_height",
        ["left_stem", "bottom_curve", "right_stem", "terminal"],
        ["bottom_curve_cut", "inner_gap_loss", "terminal_fragment"],
        ["terminal_style", "curve_depth"],
        "coverage",
        "Lowercase open bowl without a counter."
    ),
    glyph_dossier(
        "L_v",
        "v",
        "lowercase",
        "chevron",
        1,
        1,
        0,
        0,
        "x_height",
        ["two_diagonals", "bottom_vertex"],
        ["vertex_fragment", "diagonal_cut", "thin_vertex"],
        ["vertex_angle", "stroke_contrast"],
        "coverage",
        "Compact acute-vertex test."
    ),
    glyph_dossier(
        "L_w",
        "w",
        "lowercase",
        "double_chevron",
        1,
        1,
        0,
        0,
        "x_height",
        ["repeated_diagonals", "two_bottom_vertices", "central_peak"],
        ["vertex_fragment", "narrow_gap", "multi_diagonal_cut"],
        ["width", "joined_or_crossed_form"],
        "coverage",
        "Compact repeated-diagonal test."
    ),
    glyph_dossier(
        "L_x",
        "x",
        "lowercase",
        "diagonal_cross",
        1,
        1,
        0,
        0,
        "x_height",
        ["two_diagonals", "central_crossing"],
        ["crossing_cut", "thin_center", "diagonal_fragment"],
        ["crossing_height", "stroke_contrast"],
        "coverage",
        "Compact diagonal crossing test."
    ),
    glyph_dossier(
        "L_y",
        "y",
        "lowercase",
        "fork_descender",
        1,
        1,
        0,
        0,
        "descender",
        ["upper_fork", "junction", "descender"],
        ["junction_cut", "descender_fragment", "fork_fragment"],
        ["curved_or_diagonal_descender", "junction_height"],
        "coverage",
        "Tests a fork flowing into a descender."
    ),
    glyph_dossier(
        "L_z",
        "z",
        "lowercase",
        "horizontal_diagonal",
        1,
        1,
        0,
        0,
        "x_height",
        ["top_bar", "diagonal", "bottom_bar"],
        ["diagonal_cut", "corner_fragment", "thin_bar"],
        ["bar_length", "diagonal_angle"],
        "coverage",
        "Compact horizontal-diagonal test."
    )
];
