//////////////////////////////////////////////////////////////////////
// LibFile: uppercase_glyphs.scad
// Project: Glyph Dossier
// FileGroup: Character Registry
// FileSummary: Character-level dossiers for A through Z.
//////////////////////////////////////////////////////////////////////

UPPERCASE_GLYPHS = [
    glyph_dossier(
        "U_A",
        "A",
        "uppercase",
        "apex_crossbar",
        1,
        1,
        1,
        1,
        "cap",
        ["diagonal_strokes", "crossbar", "counter", "acute_apex"],
        ["apex_fragment", "crossbar_cut", "counter_collapse", "thin_inner_vertex"],
        ["apex_angle", "crossbar_height", "stroke_contrast"],
        "primary",
        "Primary diagonal, counter, crossbar, and acute-corner test."
    ),
    glyph_dossier(
        "U_B",
        "B",
        "uppercase",
        "stem_double_bowl",
        1,
        1,
        2,
        2,
        "cap",
        ["vertical_stem", "upper_bowl", "lower_bowl", "central_waist"],
        ["waist_fragment", "counter_collapse", "bowl_boundary_cut"],
        ["bowl_balance", "waist_position", "stroke_contrast"],
        "primary",
        "Tests two counters and unequal curved regions joined to one stem."
    ),
    glyph_dossier(
        "U_C",
        "C",
        "uppercase",
        "open_curve",
        1,
        1,
        0,
        0,
        "cap",
        ["open_curve", "upper_terminal", "lower_terminal"],
        ["terminal_fragment", "gap_closure", "curve_faceting"],
        ["terminal_angle", "aperture_width", "stroke_contrast"],
        "coverage",
        "Tests a continuous open curve and separated terminals."
    ),
    glyph_dossier(
        "U_D",
        "D",
        "uppercase",
        "stem_single_bowl",
        1,
        1,
        1,
        1,
        "cap",
        ["vertical_stem", "outer_bowl", "counter"],
        ["counter_collapse", "stem_bowl_cut", "curve_faceting"],
        ["bowl_width", "stroke_contrast"],
        "coverage",
        "Tests a straight stem joined to one large curved counter."
    ),
    glyph_dossier(
        "U_E",
        "E",
        "uppercase",
        "rectilinear_comb",
        1,
        1,
        0,
        0,
        "cap",
        ["vertical_stem", "top_arm", "middle_arm", "bottom_arm"],
        ["short_arm_fragment", "junction_cut", "arm_thickness_loss"],
        ["middle_arm_length", "serif_form"],
        "coverage",
        "Tests three horizontal arms with unequal lengths."
    ),
    glyph_dossier(
        "U_F",
        "F",
        "uppercase",
        "open_rectilinear_comb",
        1,
        1,
        0,
        0,
        "cap",
        ["vertical_stem", "top_arm", "middle_arm"],
        ["short_arm_fragment", "junction_cut", "bottom_balance"],
        ["middle_arm_length", "serif_form"],
        "coverage",
        "Tests an asymmetric open rectilinear structure."
    ),
    glyph_dossier(
        "U_G",
        "G",
        "uppercase",
        "open_curve_spur",
        1,
        1,
        0,
        0,
        "cap",
        ["open_curve", "horizontal_spur", "inner_terminal"],
        ["spur_fragment", "gap_closure", "curve_spur_cut"],
        ["spur_length", "aperture_width", "bar_style"],
        "coverage",
        "Tests an open curve interrupted by an interior spur."
    ),
    glyph_dossier(
        "U_H",
        "H",
        "uppercase",
        "parallel_stems_crossbar",
        1,
        1,
        0,
        0,
        "cap",
        ["left_stem", "right_stem", "crossbar"],
        ["crossbar_cut", "junction_cut", "unequal_stem_sections"],
        ["crossbar_height", "stroke_contrast"],
        "coverage",
        "Simple control glyph for two stems and one crossbar."
    ),
    glyph_dossier(
        "U_I",
        "I",
        "uppercase",
        "single_stem",
        1,
        1,
        0,
        0,
        "cap",
        ["central_stem"],
        ["narrow_part", "serif_fragment", "orientation_ambiguity"],
        ["serifed", "sans_serif", "top_bottom_bars"],
        "coverage",
        "Tests the narrowest common uppercase form and serif dependence."
    ),
    glyph_dossier(
        "U_J",
        "J",
        "uppercase",
        "hooked_stem",
        1,
        1,
        0,
        0,
        "cap",
        ["top_arm", "vertical_stem", "bottom_hook"],
        ["hook_fragment", "top_arm_cut", "asymmetric_balance"],
        ["top_bar", "hook_depth"],
        "coverage",
        "Tests a long stem ending in one curved hook."
    ),
    glyph_dossier(
        "U_K",
        "K",
        "uppercase",
        "stem_diagonal_fork",
        1,
        1,
        0,
        0,
        "cap",
        ["vertical_stem", "upper_diagonal", "lower_diagonal", "central_junction"],
        ["junction_cut", "diagonal_fragment", "acute_inner_corner"],
        ["junction_height", "diagonal_angle"],
        "coverage",
        "Tests two diagonals meeting one stem at a concentrated junction."
    ),
    glyph_dossier(
        "U_L",
        "L",
        "uppercase",
        "right_angle",
        1,
        1,
        0,
        0,
        "cap",
        ["vertical_stem", "bottom_arm"],
        ["corner_cut", "bottom_arm_fragment", "orientation_imbalance"],
        ["bottom_arm_length", "serif_form"],
        "coverage",
        "Simple right-angle control glyph."
    ),
    glyph_dossier(
        "U_M",
        "M",
        "uppercase",
        "multi_stem_diagonal",
        1,
        1,
        0,
        0,
        "cap",
        ["outer_stems", "inward_diagonals", "central_valley"],
        ["valley_fragment", "diagonal_cut", "narrow_internal_gap"],
        ["vertical_sides", "sloped_sides", "valley_depth"],
        "coverage",
        "Tests multiple long strokes and a high central valley."
    ),
    glyph_dossier(
        "U_N",
        "N",
        "uppercase",
        "stems_diagonal_bridge",
        1,
        1,
        0,
        0,
        "cap",
        ["left_stem", "right_stem", "long_diagonal"],
        ["diagonal_cut", "junction_cut", "thin_diagonal"],
        ["diagonal_angle", "stroke_contrast"],
        "coverage",
        "Tests one uninterrupted diagonal between full-height stems."
    ),
    glyph_dossier(
        "U_O",
        "O",
        "uppercase",
        "closed_ring",
        1,
        1,
        1,
        1,
        "cap",
        ["outer_curve", "counter", "continuous_ring"],
        ["counter_collapse", "ring_thickness_loss", "curve_faceting"],
        ["oval_width", "stroke_contrast", "near_circular"],
        "primary",
        "Primary closed-ring and counter-preservation test."
    ),
    glyph_dossier(
        "U_P",
        "P",
        "uppercase",
        "stem_upper_bowl",
        1,
        1,
        1,
        1,
        "cap",
        ["vertical_stem", "upper_bowl", "counter", "open_lower_region"],
        ["bowl_cut", "counter_collapse", "stem_bowl_junction"],
        ["bowl_height", "bowl_width"],
        "coverage",
        "Tests one counter concentrated in the upper half."
    ),
    glyph_dossier(
        "U_Q",
        "Q",
        "uppercase",
        "ring_tail",
        1,
        1,
        1,
        1,
        "cap",
        ["closed_ring", "counter", "tail"],
        ["tail_fragment", "ring_tail_cut", "counter_collapse"],
        ["tail_direction", "tail_length", "internal_or_external_tail"],
        "coverage",
        "Tests a ring with a small directional extension."
    ),
    glyph_dossier(
        "U_R",
        "R",
        "uppercase",
        "stem_bowl_leg",
        1,
        1,
        1,
        1,
        "cap",
        ["vertical_stem", "upper_bowl", "counter", "diagonal_leg"],
        ["leg_fragment", "bowl_leg_junction", "counter_collapse"],
        ["leg_angle", "bowl_size"],
        "coverage",
        "Combines a counter with a diagonal outgoing leg."
    ),
    glyph_dossier(
        "U_S",
        "S",
        "uppercase",
        "reversing_curve",
        1,
        1,
        0,
        0,
        "cap",
        ["upper_curve", "lower_curve", "narrow_waist", "reversal"],
        ["waist_fragment", "curve_cut", "terminal_fragment"],
        ["upper_lower_balance", "terminal_angle", "stroke_contrast"],
        "primary",
        "Primary test for reversing curvature and a narrow central waist."
    ),
    glyph_dossier(
        "U_T",
        "T",
        "uppercase",
        "topbar_stem",
        1,
        1,
        0,
        0,
        "cap",
        ["top_bar", "central_stem"],
        ["top_bar_fragment", "junction_cut", "narrow_stem"],
        ["bar_width", "serif_form"],
        "coverage",
        "Tests a wide unsupported-looking top relation to a narrow stem."
    ),
    glyph_dossier(
        "U_U",
        "U",
        "uppercase",
        "parallel_stems_bottom_curve",
        1,
        1,
        0,
        0,
        "cap",
        ["left_stem", "right_stem", "bottom_curve"],
        ["bottom_curve_cut", "stem_curve_junction", "inner_gap_loss"],
        ["bottom_roundness", "stem_parallelism"],
        "coverage",
        "Tests two stems joined by one lower curve."
    ),
    glyph_dossier(
        "U_V",
        "V",
        "uppercase",
        "chevron",
        1,
        1,
        0,
        0,
        "cap",
        ["left_diagonal", "right_diagonal", "acute_bottom_vertex"],
        ["bottom_vertex_fragment", "diagonal_cut", "thin_vertex"],
        ["vertex_angle", "stroke_contrast"],
        "coverage",
        "Tests a downward acute vertex formed by two diagonals."
    ),
    glyph_dossier(
        "U_W",
        "W",
        "uppercase",
        "double_chevron",
        1,
        1,
        0,
        0,
        "cap",
        ["four_diagonal_segments", "two_bottom_vertices", "central_peak"],
        ["vertex_fragment", "narrow_internal_gap", "multi_diagonal_cut"],
        ["width", "central_peak_height", "crossed_or_joined_form"],
        "coverage",
        "Tests repeated diagonals and multiple acute transitions."
    ),
    glyph_dossier(
        "U_X",
        "X",
        "uppercase",
        "diagonal_cross",
        1,
        1,
        0,
        0,
        "cap",
        ["two_diagonals", "central_crossing"],
        ["crossing_cut", "thin_center", "diagonal_fragment"],
        ["crossing_height", "stroke_contrast"],
        "coverage",
        "Tests two long diagonals sharing one central crossing."
    ),
    glyph_dossier(
        "U_Y",
        "Y",
        "uppercase",
        "fork_stem",
        1,
        1,
        0,
        0,
        "cap",
        ["upper_fork", "central_junction", "lower_stem"],
        ["junction_cut", "fork_fragment", "narrow_stem"],
        ["junction_height", "fork_angle"],
        "coverage",
        "Tests a three-way junction and a long lower stem."
    ),
    glyph_dossier(
        "U_Z",
        "Z",
        "uppercase",
        "horizontal_diagonal",
        1,
        1,
        0,
        0,
        "cap",
        ["top_bar", "long_diagonal", "bottom_bar"],
        ["diagonal_cut", "corner_fragment", "bar_diagonal_junction"],
        ["diagonal_angle", "bar_length"],
        "primary",
        "Primary test for a long diagonal crossing multiple future sections."
    )
];
