//////////////////////////////////////////////////////////////////////
// LibFile: portable_section_quality_reporting.scad
// Project: Glyph Dossier
// FileGroup: Portable Section Quality Reporting
// FileSummary: Reports thresholds, summaries, and diagnostic records.
//////////////////////////////////////////////////////////////////////

module report_portable_section_quality_summary(
    set_record,
    glyph,
    records,
    small_component_area,
    thin_component_estimate,
    vertex_cut_distance,
    short_seam_length,
    counter_segment_count,
    boundary_tolerance,
    bed_x,
    bed_y
) {
    echo(
        "PORTABLE_QUALITY_SET_ID",
        set_record[PFS_ID]
    );
    echo(
        "PORTABLE_QUALITY_GLYPH_ID",
        glyph[PG_ID]
    );
    echo(
        "PORTABLE_QUALITY_RECORD_COUNT",
        len(records)
    );
    echo(
        "PORTABLE_QUALITY_REVIEW_COUNT",
        portable_quality_review_count(records)
    );
    echo(
        "PORTABLE_QUALITY_CLEAR_COUNT",
        portable_quality_clear_count(records)
    );
    echo(
        "PORTABLE_QUALITY_EMPTY_COUNT",
        portable_quality_empty_count(records)
    );
    echo(
        "PORTABLE_QUALITY_REVIEW_OBJECT_IDS",
        portable_quality_review_object_ids(records)
    );
    echo(
        "PORTABLE_QUALITY_TOTAL_SHARED_SEAM_MM",
        portable_quality_total_shared_seam(
            records
        )
    );
    echo(
        "PORTABLE_QUALITY_FLAG_COUNTS",
        [
            [
                PORTABLE_QUALITY_FLAG_MULTIPLE,
                portable_quality_flag_count(
                    records,
                    PORTABLE_QUALITY_FLAG_MULTIPLE
                )
            ],
            [
                PORTABLE_QUALITY_FLAG_SMALL,
                portable_quality_flag_count(
                    records,
                    PORTABLE_QUALITY_FLAG_SMALL
                )
            ],
            [
                PORTABLE_QUALITY_FLAG_THIN,
                portable_quality_flag_count(
                    records,
                    PORTABLE_QUALITY_FLAG_THIN
                )
            ],
            [
                PORTABLE_QUALITY_FLAG_SHORT_SEAM,
                portable_quality_flag_count(
                    records,
                    PORTABLE_QUALITY_FLAG_SHORT_SEAM
                )
            ],
            [
                PORTABLE_QUALITY_FLAG_VERTEX,
                portable_quality_flag_count(
                    records,
                    PORTABLE_QUALITY_FLAG_VERTEX
                )
            ],
            [
                PORTABLE_QUALITY_FLAG_COUNTER,
                portable_quality_flag_count(
                    records,
                    PORTABLE_QUALITY_FLAG_COUNTER
                )
            ],
            [
                PORTABLE_QUALITY_FLAG_BED,
                portable_quality_flag_count(
                    records,
                    PORTABLE_QUALITY_FLAG_BED
                )
            ]
        ]
    );
    echo(
        "PORTABLE_QUALITY_THRESHOLDS",
        [
            "small_component_area_mm2",
            small_component_area,
            "thin_component_estimate_mm",
            thin_component_estimate,
            "vertex_cut_distance_mm",
            vertex_cut_distance,
            "short_seam_length_mm",
            short_seam_length,
            "counter_segment_count",
            counter_segment_count,
            "boundary_tolerance_mm",
            boundary_tolerance,
            "bed_mm",
            [bed_x, bed_y]
        ]
    );
    echo(
        "PORTABLE_QUALITY_THICKNESS_POLICY",
        "Estimate = component area / maximum component bounding-box span."
    );
    echo(
        "PORTABLE_QUALITY_COUNTER_POLICY",
        "Candidate only: multiple shared seam boundary intervals."
    );
    echo(
        "PORTABLE_QUALITY_ACTION_POLICY",
        "Report only; no cut is moved automatically."
    );
}

module report_portable_section_quality_manifest(
    records
) {
    echo(
        "PORTABLE_QUALITY_MANIFEST_COUNT",
        len(records)
    );

    for (record = records)
        echo(
            "PORTABLE_QUALITY_MANIFEST_ENTRY",
            [
                record[PSQ_OBJECT_ID],
                "section_id",
                record[PSQ_SECTION_ID],
                "index",
                [
                    record[PSQ_COLUMN],
                    record[PSQ_ROW]
                ],
                "status",
                record[PSQ_STATUS],
                "flags",
                record[PSQ_FLAGS],
                "area_mm2",
                record[PSQ_AREA],
                "components",
                record[PSQ_COMPONENT_COUNT],
                "component_areas_mm2",
                record[PSQ_COMPONENT_AREAS],
                "smallest_component_area_mm2",
                record[PSQ_SMALLEST_COMPONENT_AREA],
                "min_component_extent_mm",
                record[PSQ_MIN_COMPONENT_EXTENT],
                "min_thickness_estimate_mm",
                record[PSQ_MIN_THICKNESS_ESTIMATE],
                "seam_lengths_l_r_b_t_mm",
                record[PSQ_SEAM_LENGTHS],
                "seam_segments_l_r_b_t",
                record[PSQ_SEAM_SEGMENT_COUNTS],
                "shortest_shared_seam_mm",
                record[PSQ_SHORTEST_SEAM_LENGTH],
                "min_vertex_cut_distance_mm",
                record[PSQ_MIN_VERTEX_CUT_DISTANCE],
                "counter_cut_candidate",
                record[PSQ_COUNTER_CUT_CANDIDATE],
                "fragment_bounds",
                record[PSQ_FRAGMENT_BOUNDS],
                "fragment_size_mm",
                record[PSQ_FRAGMENT_SIZE],
                "bed_fit",
                record[PSQ_BED_FIT]
            ]
        );
}
