//////////////////////////////////////////////////////////////////////
// LibFile: portable_normalization_reporting.scad
// Project: Glyph Dossier
// FileGroup: Portable Normalization Reporting
// FileSummary: Reports exact source and normalized profile metrics.
//////////////////////////////////////////////////////////////////////

module report_generic_portable_normalization(
    set_record,
    glyph,
    target_height
) {
    echo(
        "PORTABLE_NORMALIZATION_SET_ID",
        set_record[PFS_ID]
    );
    echo(
        "PORTABLE_NORMALIZATION_FAMILY",
        set_record[PFS_FAMILY]
    );
    echo(
        "PORTABLE_NORMALIZATION_STYLE",
        set_record[PFS_STYLE]
    );
    echo(
        "PORTABLE_NORMALIZATION_GLYPH_ID",
        glyph[PG_ID]
    );
    echo(
        "PORTABLE_NORMALIZATION_CHARACTER",
        glyph[PG_CHARACTER]
    );
    echo(
        "PORTABLE_NORMALIZATION_EXACT_BOUNDS",
        glyph[PG_EXACT_BOUNDS]
    );
    echo(
        "PORTABLE_NORMALIZATION_REGION_BOUNDS",
        glyph[PG_REGION_BOUNDS]
    );
    echo(
        "PORTABLE_NORMALIZATION_SOURCE_WIDTH",
        portable_glyph_width(glyph)
    );
    echo(
        "PORTABLE_NORMALIZATION_SOURCE_HEIGHT",
        portable_glyph_height(glyph)
    );
    echo(
        "PORTABLE_NORMALIZATION_SOURCE_BOTTOM",
        portable_source_bottom(glyph)
    );
    echo(
        "PORTABLE_NORMALIZATION_SOURCE_TOP",
        portable_source_top(glyph)
    );
    echo(
        "PORTABLE_NORMALIZATION_SOURCE_CENTER_X",
        portable_source_center_x(glyph)
    );
    echo(
        "PORTABLE_NORMALIZATION_SCALE",
        portable_target_scale(
            glyph,
            target_height
        )
    );
    echo(
        "PORTABLE_NORMALIZATION_BOUNDS_MM",
        portable_normalized_bounds(
            glyph,
            target_height
        )
    );
    echo(
        "PORTABLE_NORMALIZATION_WIDTH_MM",
        portable_normalized_width(
            glyph,
            target_height
        )
    );
    echo(
        "PORTABLE_NORMALIZATION_HEIGHT_MM",
        portable_normalized_height(
            glyph,
            target_height
        )
    );
    echo(
        "PORTABLE_NORMALIZATION_BASELINE_Y_MM",
        portable_normalized_baseline_y(
            glyph,
            target_height
        )
    );
    echo(
        "PORTABLE_NORMALIZATION_ADVANCE_WIDTH_MM",
        portable_normalized_advance_width(
            glyph,
            target_height
        )
    );
    echo(
        "PORTABLE_NORMALIZATION_COMPONENTS",
        glyph[PG_COMPONENT_COUNT]
    );
    echo(
        "PORTABLE_NORMALIZATION_COUNTERS",
        glyph[PG_COUNTER_COUNT]
    );
    echo(
        "PORTABLE_NORMALIZATION_SOURCE_SHA256",
        glyph[PG_SOURCE_SHA256]
    );
    echo(
        "PORTABLE_NORMALIZATION_ANCHOR",
        "visible-center-bottom"
    );
    echo(
        "PORTABLE_NORMALIZATION_TEXT_CALL",
        false
    );
}
